name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Docker Compose Up
        run: |
          sudo docker compose up -d
          sudo docker compose ps